name: Run CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**/*.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Validate Locale
      uses: Yellow-Dog-Man/locale-checker-action@v1.0